### ISSUE TITLE
AudioProcessorValueTreeState::SliderAttachment() does not respect skew of the parameters NormalisableRange (with fix/low hanging fruit :) )

### ISSUE THREAD

**Issue by beschulz** [julianstorer/JUCE#101]
First of all: the AudioProcessorValueTreeState is pretty awesome. I was able to throw away a lot of code I had to write to syncronize parameters between the UI and the processor. Well done.

The Problem:
I'm using
```c++
state.createAndAddParameter(... NormalisableRange<float>(-100.0f, 0.0f, -6.0f, skewFactor))
```
where skewFactor is calculated as is ```Slider::setSkewFactorFromMidPoint();``` roughtly 11.2 in this case.

I then use
```c++
new AudioProcessorValueTreeState::SliderAttachment(filter->state, "gain", *gain)
```
in my AudioProcessorEditor to keep the values in sync.

While the double-click return value is set, the skew is not.

The fix is to simply add:
```c++
slider.setSkewFactor(range.skew);
```

in ```juce_AudioProcessorValueTreeState.cpp(384)```

**Comment by tpoole** [comment]
Fixed in 19d654d43ae6130588f5253f1964d9a321589ecc.
