### ISSUE TITLE
Memory Leak in MouseCursorHelpers::fromHIServices

### ISSUE THREAD

**Issue by hm1992** [julianstorer/JUCE#110]
Please include:

On startup of JUCE UI I am getting memory leaks reported in Instruments. NSImage in MouseCursorHelpers::fromHIServices. OSX 10.11 64bit. Adding [originalImage release]; as below seems to solve it. Unfortunately I don't have a test program. My knowledge of OSX APIs (thanks to the ease of use of JUCE...) is terrible, so this might be way off.

    const String cursorPath (String ("/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/"
                                        "HIServices.framework/Versions/A/Resources/cursors/")
                                + filename);

    NSImage* originalImage = [[NSImage alloc] initByReferencingFile: juceStringToNS (cursorPath + "/cursor.pdf")];
    NSSize originalSize = [originalImage size];
    NSImage* resultImage   = [[NSImage alloc] initWithSize: originalSize];

    for (int scale = 1; scale <= 4; ++scale)
    {
        NSAffineTransform* scaleTransform = [NSAffineTransform transform];
        [scaleTransform scaleBy: (float) scale];

        if (CGImageRef rasterCGImage = [originalImage CGImageForProposedRect: nil
                                                                        context: nil
                                                                        hints: [NSDictionary dictionaryWithObjectsAndKeys:
                                                                                    NSImageHintCTM, scaleTransform, nil]])
        {
            NSBitmapImageRep* imageRep = [[NSBitmapImageRep alloc] initWithCGImage: rasterCGImage];
            [imageRep setSize: originalSize];

            [resultImage addRepresentation: imageRep];
            [imageRep release];
        }
        else
        {
            return nil;
        }
    }

    [originalImage release]; // <----

    NSDictionary* info = [NSDictionary dictionaryWithContentsOfFile: juceStringToNS (cursorPath + "/info.plist")];

    const float hotspotX = (float) [[info valueForKey: nsStringLiteral ("hotx")] doubleValue];
    const float hotspotY = (float) [[info valueForKey: nsStringLiteral ("hoty")] doubleValue];

    return fromNSImage (resultImage, NSMakePoint (hotspotX, hotspotY));

**Comment by hogliux** [comment]
Yes thank you!
