### ISSUE TITLE
Resize broken under Samplitude X3!

### ISSUE THREAD

**Issue by talaviram** [julianstorer/JUCE#139]
Please include:

  1) Compile juce demo plugin under VS2015 Debug x64.
  2) Copy .vst3 to VST3 folder (C:\Program Files\Common Files\VST3\)
  3) Launch Samplitude X3 and Insert on any track juce demo plugin.
  4) Resize from resize corner handler.
  Result: it's looping / stuck instead of simply resizing properly.

I've used latest dev:
commit a816a446863b4b1faa43c8bbd60b8d3283d1ff3a
Author: hogliux <fabian.renn@gmail.com>
Date:   Sun Dec 4 12:31:23 2016 +0000

    Disabled Ableton Live's plug-in auto-suspend if the plug-in reports an infinite tail-time

**Comment by tpoole** [comment]
This is fixed on the develop branch.

**Comment by talaviram** [comment]
Tested. works as expected.
Closed IMHO.
