### ISSUE TITLE
Memory leak: ChoicePropertyComponent with CallOutBox

### ISSUE THREAD

**Issue by jzrake** [julianstorer/JUCE#145]
I get a memory leak when I combine a PropertyPanel with CallOutBox::launchAsynchronously. The problem only occurs when:

1. The PropertyPanel includes a ChoicePropertyComponent.
2. The application exits before the CallOutBox is destroyed.

```
JUCE v4.3.0
JUCE Assertion failure in juce_DeletedAtShutdown.cpp:70
```

If the CallOutBox is destroyed before the application quits, or if there is no ChoicePropertyComponent in the PropertyPanel, then there is no problem. I am on OSX 10.10.

Many apologies if this is user error. Below is a diff which should reproduce the problem in the JUCE demo application. Hit the "Click to change color..." button on the "Buttons" tab of the "Tabs and Widgets" section.

```
diff --git a/examples/Demo/Source/Demos/WidgetsDemo.cpp b/examples/Demo/Source/Demos/WidgetsDemo.cpp
index f5886f8..eb60728 100644
--- a/examples/Demo/Source/Demos/WidgetsDemo.cpp
+++ b/examples/Demo/Source/Demos/WidgetsDemo.cpp
@@ -78,14 +78,22 @@ public:
 
     void clicked() override
     {
-        ColourSelector* colourSelector = new ColourSelector();
-        colourSelector->setName ("background");
-        colourSelector->setCurrentColour (findColour (TextButton::buttonColourId));
-        colourSelector->addChangeListener (this);
-        colourSelector->setColour (ColourSelector::backgroundColourId, Colours::transparentBlack);
-        colourSelector->setSize (300, 400);
-
-        CallOutBox::launchAsynchronously (colourSelector, getScreenBounds(), nullptr);
+        Value foo;
+        StringArray keys;
+        Array<var> vals;
+
+        keys.add("key");
+        vals.add("value");
+        ChoicePropertyComponent *colours = new ChoicePropertyComponent(foo,
+                                                                       "foo",
+                                                                       keys,
+                                                                       vals);
+        Array<PropertyComponent*> comps;
+        comps.add(colours);
+        PropertyPanel *panel = new PropertyPanel;
+        panel->addSection("Foo", comps);
+        panel->setSize(128, 128);
+        CallOutBox::launchAsynchronously (panel, getScreenBounds(), nullptr);
     }
 
     void changeListenerCallback (ChangeBroadcaster* source) override

```

**Comment by jzrake** [comment]
Update:

The leaked object is a TypefaceCache, which is a singleton and so inherits DeletedAtShutdown. Is it trying to re-instantiate itself somehow? I found some other discussion of leaks related to TypefaceCache here:

https://forum.juce.com/t/juce-graphics-command-line-leak/12903

I fiddled with the ScopedJuceInitialiser_GUI class, as Jules recommended in that discussion, but without any success. One other piece of information: the problem goes away if the ChoicePropertyComponent code is modified by commenting out the line where the ComboBox member is added as a child component. Of course this means it is not displayed, so it's not a solution.

**Comment by julianstorer** [comment]
As discussed on the forum, if you leave the callout box open when your app quits, then of course there will be leaks. Solution is to clean up your modal components before quitting, but this isn't something we can or should try to fix in the library itself.
