### ISSUE TITLE
Please add possibility to view JUCE version in Projucer.exe

### ISSUE THREAD

**Issue by CodingSpiderFox** [julianstorer/JUCE#157]
As a developer, I want to easily be able to get the information about which exact version (major.miner.maitenance / build / revision) of JUCE i have installed in Projucer.exe which is the main entry point for me to create new Projects.

Maybe an "About" menu entry will do the job.

**Comment by julianstorer** [comment]
There is no global version number, but when you select a module in the config tab, it shows the version for that module.
