### ISSUE TITLE
Projucer won't launch on Ubuntu 14.04 

### ISSUE THREAD

**Issue by Darkpingouin** [julianstorer/JUCE#164]
I am having a trouble launching the Projucer binary on Ubuntu 14.04 64-bits system.
I re-downloaded the sources and the problem is still here. I have this error : 

```
./Projucer
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 10 requests (10 known processed) with 0 events remaining.
```

The demo example works tho. It is just the Projucer binary that seems to have this problem.
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212032-186542375_9-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by Darkpingouin** [comment]
Never mind I recompiled the source and it works fine.

**Comment by kushal4** [comment]
how did you run it on ubuntu 14.04 please help

**Comment by Darkpingouin** [comment]
@kushal4 Just go to the source files and recompile them it should work fine. Also make sure that you have all the dependencies installed : https://forum.juce.com/t/list-of-juce-dependencies-under-linux/15121
