### ISSUE TITLE
Compiling with c++14 Causes Implicit Conversion Warning in VST Wrapper

### ISSUE THREAD

**Issue by RustyPine** [julianstorer/JUCE#171]
`JUCE/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:445:65: Implicit conversion changes signedness: 'int' to 'unsigned long'`

1) 
- open MultiOutSynth project
- in Xcode settings select C++14 for C++ Language Standard
- build
3) macOS Sierra 10.12.3
4) 64
6) VST2
![screen shot 2017-03-15 at 4 39 55 pm](https://cloud.githubusercontent.com/assets/26398244/23975558/b58285ac-099e-11e7-9ced-a2a21ac50817.png)
![screen shot 2017-03-15 at 4 40 23 pm](https://cloud.githubusercontent.com/assets/26398244/23975559/b582a672-099e-11e7-941f-17f83b8ce343.png)

**Comment by julianstorer** [comment]
Thanks, should be OK now.
