### ISSUE TITLE
Suspicious code fragments found by PVS-Studio

### ISSUE THREAD

**Issue by VasilievSerg** [julianstorer/JUCE#179]
Hello,
I have found a few issues using PVS-Studio analyzer. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

Some of the analyzer warnings:

- V501 There are identical sub-expressions 'gradCol1.isOpaque()' to the left and to the right of the '&&' operator. Projucer jucer_filltype.h 260 
[A link to the source code]( https://github.com/julianstorer/JUCE/blob/75cd666a61f31eaa3ee6c6d9ad97bc404878a0d8/extras/Projucer/Source/ComponentEditor/paintelements/jucer_FillType.h#L260)
- V595 The 'owner' pointer was utilized before it was verified against nullptr. Check lines: 315, 317. Projucer jucer_paintelement.cpp 315 
[A link to the source code]( https://github.com/julianstorer/JUCE/blob/75cd666a61f31eaa3ee6c6d9ad97bc404878a0d8/extras/Projucer/Source/ComponentEditor/paintelements/jucer_PaintElement.cpp#L315)
- V547 Expression 'target != nullptr' is always true. Projucer juce_componentpeer.cpp 275 
[A link to the source code]( https://github.com/julianstorer/JUCE/blob/75cd666a61f31eaa3ee6c6d9ad97bc404878a0d8/modules/juce_gui_basics/windows/juce_ComponentPeer.cpp#L275)

There aren't all the issues found by the analyzer, just several of them. It would be much better if the developers had a look at the warnings themselves, because I am not familiar with the code. :)

In addition, I suggest having a look at the emails, sent from @pvs-studio.com.

Best regards,
Sergey Vasiliev

**Comment by julianstorer** [comment]
Thanks Sergey - lucky there was nothing serious there, but I've tidied those up. (BTW the develop branch is much more recent than whatever you were checking, so you might want to use that instead)

**Comment by VasilievSerg** [comment]
@julianstorer , indeed, I haven't noticed the branch 'develop'. Perhaps, it would be interesting for you to have a look yourself and see if there will be something interesting in the branch 'develop'. :)
