### ISSUE TITLE
Mac menu bar flashes when invoking commands registered with dontTriggerVisualFeedback flag

### ISSUE THREAD

**Issue by jearnshaw** [julianstorer/JUCE#90]
The dontTriggerVisualFeedback flag should be checked in juce_mac_MainMenu.mm menuCommandInvoked() before flashMenuBar.

In addition to this, it seems commands registered with modifier keys or keycodes flash the OS X menu bar twice when the shortcut keys are pressed. This can be observed in the JuceDemo App -> Tabs & Widgets -> Use Native Menu Bar -> Press Command + P

**Comment by julianstorer** [comment]
Thanks, will push a fix for this today..
