### ISSUE TITLE
Projucer steals keystrokes from JIT components / running app

### ISSUE THREAD

**Issue by willricemusic** [julianstorer/JUCE#96]
**STR:**

1. Open JuceDemo.jucer in Projucer 4.2.3
2. Build > Enable Compilation
3. Build > Launch Application
4. In the running Demo app, browse to the Code Editor, or HTTP demos
5. Attempt data entry from keyboard

**Expected behaviour:**

Keystroke events make it to the running application / JIT component when it is the foreground window.

**Actual behaviour:**

Keystroke events are consumed by the Projucer. If the code editor has keyboardFocus in the Projucer, then keystrokes will end up there instead of making it to the running application, even if the application / JIT component is the foreground window. If Projucer doesn't want keyboardFocus the events are discarded.

Note* This affects individual components running in the JIT engine as well as whilst running the whole application inside the Projucer.

----------
OS X 10.11.6 (64-bit)
JUCE / Projucer 4.2.3 (3592d61)
Retina MBP 13" 10,2

**Comment by tpoole** [comment]
This is fixed on the develop branch.
