### ISSUE TITLE
Incorrect #error message in JUCE_AUv3_Wrapper.mm

### ISSUE THREAD

**Issue by willricemusic** [julianstorer/JUCE#99]
[JUCE_AUv3_Wrapper.mm, Line 36: ](https://github.com/julianstorer/JUCE/blob/master/modules/juce_audio_plugin_client/AU/juce_AUv3_Wrapper.mm#L36)

`#error AUv3 needs Deployment Target OS X 10.8 or higher to compile`

should read

`#error AUv3 needs Deployment Target OS X 10.11 or higher to compile`

https://forum.juce.com/t/bug-auv3-needs-deployment-target-os-x-10-8-or-higher-to-compile-but-preprocessor-check-is-for-mac-os-x-version-10-11/18528/2

**Comment by tpoole** [comment]
This is fixed on the develop branch. Do you need it on master too?

**Comment by willricemusic** [comment]
Thanks @tpoole. No need to push it to master - it's not urgent.
